# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :beta do
      notification(subtitle: "ActiveBankWebSDK", message: "Started")
   increment_build_number({
      build_number: latest_testflight_build_number(
        app_identifier: "ai.active.activebankwebsdk"
      ) + 1
    })
  get_provisioning_profile   # invokes sigh
    build_app(workspace: "HybridSample.xcworkspace", scheme: "HybridSample")
    notification(subtitle: "ActiveBankWebSDK", message: "Compilation Ended")
    upload_to_testflight
    notification(subtitle: "ActiveBankWebSDK", message: "Testflight Released")
  end
end